### ISSUE TITLE
How you can get it working on file explorer

### ISSUE THREAD

**Issue by ghost** [Ingan121/BasicThemer2#11]
This isn't an Issue but It is a fix for an issue
1. add explorer.exe as an exception so the title bars don't disappear 
2. Install SecureUXtheme https://github.com/namazso/SecureUxTheme (this Is like UXStyle patcher but doesn't break anything)
3. Install WinRAR or 7zip
4. Patch and Apply the basic 7 theme from https://www.deviantart.com/sagorpirbd/art/Aero-7-Themes-for-Win10-Final-52397994
5. then you are finished enjoy full windows 7 theme

**Comment by Ingan121** [comment]
Thanks for information.
By the way, I think disabling ribbons and using BT2 would be better if you don't need the ribbons.
