### ISSUE TITLE
How to exclude Windows Photo Viewer window from basic theme

### ISSUE THREAD

**Issue by spayton98** [Ingan121/BasicThemer2#14]
Hey, I'm running Windows 10 20H2 and was wondering how to exclude Windows Photo Viewer from running the basic theme. I know there's no executable file for Photo Viewer and it seems only executable files can be entered into the exclusion window, but I was wondering if there is some sort of workaround. Thanks.

**Comment by Ingan121** [comment]
There's currently no way to do so until a window title/class-based exclusion gets added.

You can download and put the dwmapi.dll linked in the Extras folder into C:\Program Files\Windows Photo Viewer to make the Photo Viewer use the basic theme.

**Comment by spayton98** [comment]
Thanks for responding. I copied dwmapi32.dll to the Windows Photo Viewer folder in Program Files (copying 64-bit dwmapi.dll gave me an error message when trying to open Photo Viewer, I have a screenshot of it below). 

![image](https://user-images.githubusercontent.com/92222648/136821001-cd6c3bf3-0fe8-4dec-af12-3cd7c7fdd563.png)

I renamed it to dwmapi.dll and nothing happened. I then copied 64-bit dwmapi.dll to the Windows Photo Viewer folder in Program Files x86 and still nothing happened. I then restarted my computer but Photo Viewer still has the "glitched out" look on the bottom. Not sure what to do now.

**Comment by Ingan121** [comment]
Sorry, I remember this worked a few years ago, but when I tried this again in 10 20H2 and 11, I got the same result.
I'll add title/class-based exclusions soon, so please use this feature when it gets added.

**Comment by Filifek** [comment]
Hello, i just wanted to mention i managed to exclude Windows Photo Viewer from the basic theme by adding "dllhost.exe" to exclusion list.

**Comment by spayton98** [comment]
Thanks for the suggestion! I tried it and it worked for me too.
