### ISSUE TITLE
Classic theme support?

### ISSUE THREAD

**Issue by abbzie** [Ingan121/BasicThemer2#15]
Would it be possible to have a classic theme option? Personally i like classic theme but I don't like the screen tear.

**Comment by Ingan121** [comment]
It seems that you are using Windows 7. If so, follow the second method mentioned in [here](https://winclassic.boards.net/thread/494/acceleration-gui-aero-themes-windows), then use BasicThemer 2 to remove the Aero title bar.

If you’re on Windows 8 and later, just use [SimpleClassicTheme](https://winclassic.boards.net/thread/456/simple-classic-theme-supports-windows) without disabling DWM.
