### ISSUE TITLE
What would be great now.....

### ISSUE THREAD

**Issue by Ulti-P-Uszer** [Ingan121/BasicThemer2#17]
There was a colors basic theme that had 8 diff colors in it that worked up to Win7. it was called "Colors_2_0_For_Windows_7_Basic_by_MediaMyself" After I ran your new basic patch I tried the old colors theme in a VM also. But both of them together busted the 10 VM into a black screen of death (LOL). It truly would be great if you looked up the old basic colors theme & maybe modded it to work on 10 & 11.

**Comment by Ingan121** [comment]
This program does not modify any visual styles. You need to manually make the theme compatible with 10+ (extract some resources from the theme and put them in the default theme) then apply it with SecureUXTheme/UltraUXThemePatcher.

**Comment by Ingan121** [comment]
Found a better option: use [AccentColorizer](https://github.com/krlvm/AccentColorizer).
It changes the colors of various theme elements with your accent color.
