### ISSUE TITLE
File Explorer Breaks

### ISSUE THREAD

**Issue by DatGamerYoloYT** [Ingan121/BasicThemer2#18]
I'm using Windows 11 and when I'm using File Explorer it looks like this:
![image](https://user-images.githubusercontent.com/84749503/160299343-0b80c9a2-f7a8-45f9-a09a-eccf83316c7c.png)
There are no buttons and even the top of the window is gone.

Did I do something wrong?

**Comment by Splitwirez** [comment]
Not as far as I'm aware...that seems to just happen sometimes. I guess that's something we'll need to look into...in the meantime, add an exclusion for explorer

**Comment by DatGamerYoloYT** [comment]
wait how do i add an exclusion

**Comment by Ingan121** [comment]
> wait how do i add an exclusion

Add explorer.exe to the exclusion list.
You can also disable the new command bar with ExplorerPatcher.
