### ISSUE TITLE
Issue with 16bit programs and WineVDM

### ISSUE THREAD

**Issue by OrthodoxWindows** [Ingan121/BasicThemer2#19]
When running Win16 programs (programs developed for Windows 3.x) with WineVDM (https://github.com/otya128/winevdm), BasicThemer2 does not display the title bar correctly. On the other hand, the titles of the dialog boxes of Win16 programs are displayed correctly.

It happens that this issue relates to a Win32 program, but it is much rarer.

![otvdmw_PZT6PRy4Ys](https://user-images.githubusercontent.com/100134023/178160505-da2779a8-e1d4-43eb-9956-99188bb8573a.png)
![explorer_fqXFPwjG5v](https://user-images.githubusercontent.com/100134023/178160700-87522082-ef22-4ccf-bbf1-99ba7722f4d6.png)
![explorer_uU4ZnaMv9R](https://user-images.githubusercontent.com/100134023/178160713-49dbcba2-e5fb-4b33-89a6-038ae4396a75.png)

**Comment by Ingan121** [comment]
It is not something that BT2 could solve.

Classic and Basic frames are drawn inside the window's device context (DC), while DWM/Aero frames are rendered out of the window DC. The area for title bars/frames in the window DC is typically empty when the DWM frame is in use, and the Basic frame starts rendering when DWM frames are disabled (by killing DWM or with BT2). However, some code in the WineVDM is causing a bug that keeps the Basic frame from rendering even after BT2 disabled the DWM frame.
I found that WineVDM works well with the Basic frame if it was started while DWM is disabled, and those windows still work well after restoring DWM and using BT2 to disable the DWM frame. I tried searching codes checking composition status in WineVDM, but I couldn't find anything; I think some window rendering code is triggering the issue.
(Calling `PrintWindow()` on the window makes it render the Basic frame, but it doesn't respond to (de)activation and any mouse movements/clicks.)

BasicThemer2 only calls some DwmApis to ask for Windows to disable the DWM frame for a window; it cannot change any application behavior (besides the thing in the Detours branch - but it doesn't seem to solve this problem either).

**Comment by OrthodoxWindows** [comment]
Thank you for the answer !

To be honest, when I posted this, I had no idea what was causing the issue. If I understood correctly, the challenge is to find the faulty code in WineWDM. I don't know if it helps orientation, but I tried running WineWDM in Windows XP mode (so with composition disabled), the problem is exactly the same as with BasicThemer2.

I will try to post the issue in the WineVDM page.

**Comment by Ingan121** [comment]
The XP compatibility mode's Basic frame is similar to the BT2 one. To make WVDM work correctly, you must kill DWM completely. Try the below command in the admin cmd (tested on W11 22H2):
`pssuspend winlogon.exe && taskkill -im dwm.exe -f && \path\to\16bit.exe && timeout 5 && pssuspend -r winlogon.exe`

**Comment by Ingan121** [comment]
Confirmed [the latest WineVDM build](https://ci.appveyor.com/project/otya128/winevdm/build/job/mx813jo46hta9lqg/artifacts) fixed the issue.

![화면 캡처 2022-08-30 003255](https://user-images.githubusercontent.com/34885971/187238405-8d3f4752-f414-468e-9546-97fea95af057.png)
