### ISSUE TITLE
dwm disable

### ISSUE THREAD

**Issue by kyrox02** [Ingan121/BasicThemer2#3]
is it possible disable dwm without stutters the games? the method i use is using custom shell windows + suspend winlogon kill dwm thread in winlogon handle process its make my games a lot smoother/snappines but cause stutters like 5-10 min and then back

**Comment by Ingan121** [comment]
I don’t know. I gave up using the DWMless environment because of a lot of issues including frequent freezing and that stuttering issue. I think killing DWM in current builds of Win10 is not good for gaming.

**Comment by kyrox02** [comment]
the stutter come from ScrollWindowsExFlags i found out

**Comment by Ingan121** [comment]
Unrelated to this software, closing.
