### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Llumz** [Ingan121/BasicThemer2#4]
Hi Ingan, how did you change the texture of scrollbars/buttons/progressbars in Windows 10 like on your screenshot? https://github.com/Ingan121/BasicThemer2/blob/master/스크린샷(241).png
Default ones look more flatter, and I wanna change them too.
Thank you! :)

**Comment by Ingan121** [comment]
I used [this one](https://www.deviantart.com/sagorpirbd/art/Vista-Themes-Final-for-Win10-521781687).
This still works for 20H1 (but not tested for 20H2).
