### ISSUE TITLE
Graphical glitch with ribbons in File Explorer and Photo Gallery

### ISSUE THREAD

**Issue by Fytuf** [Ingan121/BasicThemer2#5]
I noticed that when you have ribbons enabled in File Explorer the title bar gets transparent and unclickable.
![image](https://user-images.githubusercontent.com/72277532/106937171-b0cc1300-66da-11eb-9bb6-973f877f1b19.png)

This also happens with Photo Gallery.

Is this problem fixable?

**Comment by Ingan121** [comment]
Unfortunately, there is no way to get the basic theme with explorer ribbons while keeping DWM. You have to either disable the ribbons or add Explorer to the exclusion list.

For Photo Gallery, do the exe patch and place dwmapi.dll to its directory, as mentioned in the Extras folder in this repository. Please note that its title bar will be unfunctional without the basic theme.
(explorer.exe will crash if you do this for that)
