### ISSUE TITLE
Drop .NET Framework version to 4.6 to support Windows 8.0?

### ISSUE THREAD

**Issue by Splitwirez** [Ingan121/BasicThemer2#6]
![](https://cdn.discordapp.com/attachments/660426424292737043/819006645107556402/unknown.png)
Literally no code changes needed, just change the target framework and recompile, and boom, it suddenly works on Windows 8.0 .

**Comment by Ingan121** [comment]
Doesn't it work on Windows 8.0? For me, the latest release version works on Windows 7, and older version used to work on Windows Vista. (I can't test it now as I deleted the Vista VM for disk space.)

**Comment by Splitwirez** [comment]
> Doesn't it work on Windows 8.0?

No, as it currently targets a version of .NET Framework which does not support Windows 8.0.

The target Framework version can be dropped to 4.6 without any other changes having to be made. I did this locally, and sent it to a friend to test against Windows 8.0, who then verified that it does indeed work on 8.0 after dropping the target Framework version, and provided the above screenshot.

**Comment by Ingan121** [comment]
I've just uploaded a [new version](https://github.com/Ingan121/BasicThemer2/releases/tag/v0.5.2). Could you check if it works on Windows 8.0?
It was surprising that MS even stopped the support for the .net framework on Windows 8.0.

**Comment by Splitwirez** [comment]
> I've just uploaded a [new version](https://github.com/Ingan121/BasicThemer2/releases/tag/v0.5.2). Could you check if it works on Windows 8.0?

I'll let you know as soon as I hear back.

> It was surprising that MS even stopped the support for the .net framework on Windows 8.0.

Agreed...it's probably just an artificial lockout, but still annoying.

**Comment by Splitwirez** [comment]
@Ingan121 So sorry I forgot to get back to you until now.

I did hear back, and apparently your binaries still refused to run on Windows 8.0, for precisely the same reason as before.

Might you have forgotten to rebuild before uploading the binaries for that release? (Please don't take this as an insult...FWIW it's happened to me a few times before)

**Comment by Ingan121** [comment]
Are you sure your friend downloaded the linked v0.5.2 version, which is currently marked as pre-release and thus not displayed mainly on the releases page? I'm sure I rebuilt this as this version has v0.5.2 as the version number, which I increased just for this. (I do this only before submitting a release build.)

If you are sure, I'm sure it's because of my VS's problem. It's currently broken, and it doesn't load without using the safe mode. And I couldn't load any projects (not solutions) in that mode so I can't change the build configuration with GUI, so I had to find the strings "4.7.2" and replace them with "4.6", then manually rebuilt it. (I also directly changed the version number by editing some XML files.)
I tried running devenv.exe /resetsettings which VS suggested on the error dialog, but I was stuck in the splash window. I think I have to find another solution on Google, but I don't have enough time these days. Sorry for that.

If you could find any remaining "4.7.2"s on this project, please reply with the location of it or create a pull request of it. I will then build it and upload.

**Comment by Splitwirez** [comment]
> Are you sure your friend downloaded the linked v0.5.2 version, which is currently marked as pre-release and thus not displayed mainly on the releases page? I'm sure I rebuilt this as this version has v0.5.2 as the version number, which I increased just for this. (I do this only before submitting a release build.)

Well...I linked him to that version directly, just as you did for me. I can't exactly imagine how he could've ended up downloading any other release.

> If you are sure, I'm sure it's because of my VS's problem. It's currently broken, and it doesn't load without using the safe mode. And I couldn't load any projects (not solutions) in that mode so I can't change the build configuration with GUI, so I had to find the strings "4.7.2" and replace them with "4.6", then manually rebuilt it. (I also directly changed the version number by editing some XML files.)
> I tried running devenv.exe /resetsettings which VS suggested on the error dialog, but I was stuck in the splash window. I think I have to find another solution on Google, but I don't have enough time these days. Sorry for that.

Oh dear, that can't be good. Have you considered using, say, Visual Studio Code as a band-aid solution until you have the time to investigate?

> If you could find any remaining "4.7.2"s on this project, please reply with the location of it or create a pull request of it. I will then build it and upload.

Sure thing. As I said before, I changed the target framework version to 4.6 locally, built that, and my friend confirmed that it worked without a hitch on Windows 8.0. As soon as I'm able, I'll get my fork up-to-date, push those changes, and open a PR for you.

**Comment by Ingan121** [comment]
Just fixed the problem and rebuilt it: https://github.com/Ingan121/BasicThemer2/releases/tag/v0.5.2
Please try again.

[(This worked for me.)](https://stackoverflow.com/a/51076810)

**Comment by Anixx** [comment]
Win8.1 is just a service pack for Windows 8. So, this is not surprising.

**Comment by Splitwirez** [comment]
> Just fixed the problem and rebuilt it: https://github.com/Ingan121/BasicThemer2/releases/tag/v0.5.2
> Please try again.
> 
> [(I used this method to fix the problem.)](https://stackoverflow.com/a/51076810)

@Ingan121 So sorry I forgot to get back to you...still no luck, evidently :c

**Comment by Ingan121** [comment]
[Finally got it really working on Windows 8.0!](https://user-images.githubusercontent.com/34885971/187042098-690ece55-52f3-4e73-9820-44c6211acb99.png)
It's available in the releases.

**Comment by Ingan121** [comment]
[Finally got it really working on Windows 8.0!](https://user-images.githubusercontent.com/34885971/187042098-690ece55-52f3-4e73-9820-44c6211acb99.png)
It's available in the [releases](https://github.com/Ingan121/BasicThemer2/releases/tag/v0.5.2-Final).
@Splitwirez
