### ISSUE TITLE
Doesn't seem to function correctly on Windows 10 21H1

### ISSUE THREAD

**Issue by Bonnie39** [Ingan121/BasicThemer2#9]
BasicThemer2 completely breaks the title bars of file explorer windows making them completely transparent and effectively removing the ability to close them as the buttons are also removed as well. This likely has something to do with a change in the way explorer.exe works in the newest version of Windows 10.

**Comment by ghost** [comment]
IT IS NOT FIXABLE a solution to this would be to exclude explorer.exe and install secure UX theme and use Aero7 Basic theme then you will get the Basicthemer2 title bars for all other programs but the the aero 7 title bars for windows explorer and control panel

**Comment by Bonnie39** [comment]
> IT IS NOT FIXABLE a solution to this would be to exclude explorer.exe and install secure UX theme and use Aero7 Basic theme then you will get the Basicthemer2 title bars for all other programs but the the aero 7 title bars for windows explorer and control panel

does secure UX theme and the Aero themes actually work on the latest version of Windows 10 though? At least as far as I knew those haven't been updated since like 2016

**Comment by ghost** [comment]
> > IT IS NOT FIXABLE a solution to this would be to exclude explorer.exe and install secure UX theme and use Aero7 Basic theme then you will get the Basicthemer2 title bars for all other programs but the the aero 7 title bars for windows explorer and control panel
> 
> does secure UX theme and the Aero themes actually work on the latest version of Windows 10 though? At least as far as I knew those haven't been updated since like 2016

It doesn't work on Uxstyle Patcher but it works Great on secureUXtheme Patcher the buttons are kinda big though so I set the title bar size to 20 in winaero tweaker
